package mtz

import (
	"time"
)

var (
	shanghaiLoc *time.Location
)

func init() {
	shanghaiLoc, _ = time.LoadLocation("Asia/Shanghai")
}

func LoadLocation(tz string) *time.Location {
	if tz == "" {
		return shanghaiLoc
	}
	loc, err := time.LoadLocation(tz)
	if err != nil {
		return shanghaiLoc
	}
	if loc == nil {
		return shanghaiLoc
	}
	return loc
}

func TimeZone(tz, countryCode string) string {
	if tz != "" {
		return tz
	}
	tz = timeZoneMap[countryCode]
	if tz != "" {
		return tz
	}
	return "Asia/Shanghai"
}

var timeZoneMap = map[string]string{
	"TO": "Pacific/Tongatapu",
	"AM": "Asia/Yerevan",
	"BA": "Europe/Sarajevo",
	"UY": "America/Montevideo",
	"HN": "America/Tegucigalpa",
	"GU": "Pacific/Guam",
	"AF": "Asia/Kabul",
	"AD": "Europe/Andorra",
	"FO": "Atlantic/Faroe",
	"MK": "Africa/Cairo",
	"MC": "Europe/Berlin",
	"YU": "Africa/Cairo",
	"AL": "Europe/Tirane",
	"VE": "America/Caracas",
	"SD": "Africa/Khartoum",
	"TN": "Africa/Tunis",
	"DZ": "Africa/Algiers",
	"NA": "Africa/Windhoek",
	"NR": "Pacific/Nauru",
	"MP": "Pacific/Saipan",
	"GT": "America/Guatemala",
	"TV": "Pacific/Funafuti",
	"SB": "Pacific/Guadalcanal",
	"NU": "Pacific/Niue",
	"VC": "America/St_Vincent",
	"MH": "Pacific/Majuro",
	"PF": "Pacific/Tahiti",
	"CD": "America/Sao_Paulo",
	"GG": "Europe/Guernsey",
	"KI": "Pacific/Tarawa",
	"GH": "Africa/Accra",
	"GA": "Africa/Libreville",
	"CI": "Africa/Abidjan",
	"BR": "America/Sao_Paulo",
	"CU": "America/Anguilla",
	"IR": "Asia/Tehran",
	"IQ": "Asia/Baghdad",
	"IL": "Africa/Addis_Ababa",
	"EG": "Africa/Cairo",
	"RU": "Europe/Moscow",
	"TR": "Europe/Istanbul",
	"BD": "Asia/Dhaka",
	"PK": "Asia/Karachi",
	"ID": "Asia/Jakarta",
	"SI": "Europe/Ljubljana",
	"BE": "Europe/Brussels",
	"FI": "Europe/Helsinki",
	"IT": "Europe/Rome",
	"IN": "Asia/Kolkata",
	"MX": "America/Mexico_City",
	"LU": "Europe/Luxembourg",
	"RO": "Europe/Bucharest",
	"TW": "Asia/Taipei",
	"JP": "Asia/Tokyo",
	"BT": "Asia/Thimphu",
	"ZA": "Africa/Johannesburg",
	"SE": "Europe/Stockholm",
	"MT": "Europe/Malta",
	"CA": "America/Toronto",
	"KE": "Africa/Nairobi",
	"MA": "Africa/Casablanca",
	"MY": "Asia/Kuala_Lumpur",
	"EE": "Europe/Tallinn",
	"PA": "America/Panama",
	"ET": "Africa/Addis_Ababa",
	"LT": "Europe/Vilnius",
	"HR": "Europe/Zagreb",
	"ML": "Africa/Bamako",
	"MG": "Indian/Antananarivo",
	"RW": "Africa/Kigali",
	"NE": "Africa/Lagos",
	"OM": "Asia/Muscat",
	"LK": "Asia/Colombo",
	"BG": "Europe/Sofia",
	"BH": "Asia/Bahrain",
	"CO": "America/Anguilla",
	"NO": "Europe/Oslo",
	"UG": "Africa/Kampala",
	"PT": "Europe/Lisbon",
	"BS": "America/Nassau",
	"NG": "Africa/Lagos",
	"AO": "Africa/Luanda",
	"TZ": "Africa/Dar_es_Salaam",
	"MV": "Indian/Maldives",
	"RE": "Indian/Reunion",
	"AG": "America/Antigua",
	"RS": "Europe/Belgrade",
	"IS": "Atlantic/Reykjavik",
	"KR": "Asia/Seoul",
	"DO": "America/Santo_Domingo",
	"QA": "Asia/Qatar",
	"TL": "Asia/Dili",
	"GL": "America/Godthab",
	"LI": "Europe/Vaduz",
	"KY": "America/Cayman",
	"HT": "America/Port-au-Prince",
	"MM": "Asia/Yangon",
	"SC": "Asia/Baku",
	"JM": "America/Jamaica",
	"SR": "America/Paramaribo",
	"BW": "Africa/Gaborone",
	"SM": "Europe/San_Marino",
	"AW": "America/Aruba",
	"AI": "Europe/Rome",
	"MQ": "America/Martinique",
	"NI": "America/Managua",
	"SL": "Africa/Freetown",
	"SN": "Africa/Dakar",
	"SZ": "Africa/Mbabane",
	"GI": "Europe/Gibraltar",
	"SV": "America/El_Salvador",
	"SK": "Europe/Bratislava",
	"ME": "Europe/Podgorica",
	"EC": "America/Guayaquil",
	"MW": "Africa/Blantyre",
	"CK": "Pacific/Rarotonga",
	"BB": "America/Barbados",
	"PY": "America/Asuncion",
	"BM": "Atlantic/Bermuda",
	"BJ": "Africa/Porto-Novo",
	"BZ": "America/Belize",
	"TG": "Africa/Lome",
	"GM": "Africa/Banjul",
	"GP": "America/Guadeloupe",
	"CR": "America/Costa_Rica",
	"DJ": "Africa/Djibouti",
	"CM": "Africa/Douala",
	"LR": "Africa/Monrovia",
	"KG": "Asia/Bishkek",
	"GD": "America/Grenada",
	"PR": "America/Puerto_Rico",
	"NP": "Asia/Kathmandu",
	"AR": "America/Araguaina",
	"PE": "America/Atikokan",
	"CL": "America/Araguaina",
	"JO": "Asia/Amman",
	"KW": "Asia/Kuwait",
	"SA": "Asia/Riyadh",
	"LB": "Asia/Beirut",
	"CZ": "Europe/Warsaw",
	"BY": "Europe/Minsk",
	"HU": "Europe/Budapest",
	"PL": "Europe/Warsaw",
	"AU": "Australia/Lord_Howe",
	"PH": "Asia/Brunei",
	"TH": "Asia/Bangkok",
	"SG": "Asia/Shanghai",
	"NZ": "Pacific/Apia",
	"BN": "Asia/Brunei",
	"ES": "Europe/Madrid",
	"AT": "Europe/Vienna",
	"DK": "Europe/Copenhagen",
	"GR": "Europe/Athens",
	"IE": "Europe/Dublin",
	"CH": "Europe/Zurich",
	"DE": "Europe/Berlin",
	"KH": "Asia/Phnom_Penh",
	"KZ": "Asia/Almaty",
	"LV": "Europe/Riga",
	"UA": "Europe/Kiev",
	"HK": "Asia/Hong_Kong",
	"MO": "Asia/Macau",
	"NC": "Pacific/Noumea",
	"NL": "Europe/Amsterdam",
	"FR": "Europe/Paris",
	"AZ": "Europe/Vilnius",
	"CY": "Asia/Nicosia",
	"MD": "Europe/Chisinau",
	"ZM": "Africa/Lusaka",
	"UZ": "Asia/Tashkent",
	"ZW": "Africa/Harare",
	"VA": "Europe/Vatican",
	"AE": "Asia/Dubai",
	"VN": "Asia/Ho_Chi_Minh",
	"VU": "Pacific/Efate",
	"GB": "Europe/London",
	"US": "America/New_York",
}
